# This file was generated by GoReleaser. DO NOT EDIT.
cask "bfast" do
  name "bfast"
  desc "CLI badger for registering repos with blazingly.fast and inserting the badge"
  homepage "https://blazingly.fast"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bfast"

  on_macos do
    on_intel do
      url "https://github.com/arrno/bfast/releases/download/v#{version}/bfast_#{version}_darwin_amd64.tar.gz"
      sha256 "04a696af2456d93a75b22b361c0a7d7626afea9ba3383a1f28ed7761030babdf"
    end
    on_arm do
      url "https://github.com/arrno/bfast/releases/download/v#{version}/bfast_#{version}_darwin_arm64.tar.gz"
      sha256 "64b82426816046d778439e9c1da08b4c77c2f62e098b8dbd3163ae2967e9fc9e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arrno/bfast/releases/download/v#{version}/bfast_#{version}_linux_amd64.tar.gz"
      sha256 "9351443750f0542fbe6c1a44e2157385381e67a9fb28a35ec47f93c1ae6c96af"
    end
    on_arm do
      url "https://github.com/arrno/bfast/releases/download/v#{version}/bfast_#{version}_linux_arm64.tar.gz"
      sha256 "f41d92adcf4b1d9a4308e601a7efb01dd1d7cd074e6744f7151a7b3308a108c4"
    end
  end

  # No zap stanza required
end
