# This file was generated by GoReleaser. DO NOT EDIT.
cask "bfast" do
  name "bfast"
  desc "CLI badger for registering repos with blazingly.fast and inserting the badge"
  homepage "https://blazingly.fast"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bfast"

  on_macos do
    on_intel do
      url "https://github.com/arrno/bfast/releases/download/v#{version}/bfast_#{version}_darwin_amd64.tar.gz"
      sha256 "b48f2c56c82ffa9a919126330c722798a10ab676d112d38c7647ea64630c49ae"
    end
    on_arm do
      url "https://github.com/arrno/bfast/releases/download/v#{version}/bfast_#{version}_darwin_arm64.tar.gz"
      sha256 "ab90f8da27f1b2aab4510a9eecb3cc960da702debdbad877bd5b4a5b57935447"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arrno/bfast/releases/download/v#{version}/bfast_#{version}_linux_amd64.tar.gz"
      sha256 "d75829f3821a04966b913b2462f169c98f06e57230ef99d9054fe6641ce7cabc"
    end
    on_arm do
      url "https://github.com/arrno/bfast/releases/download/v#{version}/bfast_#{version}_linux_arm64.tar.gz"
      sha256 "d471f886e9780a2cbe80db3e7353b135c8bcda3ee85435c468a1b75d25d74cb2"
    end
  end

  postflight do
    if OS.mac?
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bfast"]
    end
  end

  # No zap stanza required
end
